apiVersion: v1
data:
  csi-vsphere.conf: xxx

kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: vmware-system-csi
type: Opaque

# data xxx is the base64 encoded of:
#     [Global]
#     cluster-id = "123456789"
#     cluster-distribution = "vanilla"

#     [NetPermissions "A"]
#     ips = "*"
#     permissions = "READ_WRITE"
#     rootsquash = false

#     [VirtualCenter "xxx"]
#     insecure-flag = "true"
#     user = "xxx"
#     password = "xxx"
#     port = "443"
#     datacenters = "cPod-MYNSX" 

