apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  name: external-dns
  namespace: external-dns
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: external-dns
  annotations:
    kubernetes.io/service-account.name: external-dns
type: kubernetes.io/service-account-token
